# Generated by Django 5.1.3 on 2024-11-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaTimeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(related_name='orders', to='PizzaTimeApp.pizza'),
        ),
    ]
