# Generated by Django 5.1.3 on 2024-11-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaTimeApp', '0002_order_is_completed_alter_order_pizzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
